version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hex-rgb:
    build: HEX-RGB
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hex-rgb.rule=PathPrefix(`/hex-rgb`)"
      - "traefik.http.routers.hex-rgb.middlewares=hex-rgb-stripprefix"
      - "traefik.http.middlewares.hex-rgb-stripprefix.stripprefix.prefixes=/hex-rgb"
      - "traefik.http.services.hex-rgb.loadbalancer.server.port=3000"

  # HSL-HEX:
  #   build: hsl-hex
  #   restart: "no"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.HSL-HEX.rule=PathPrefix(`/HSL-HEX`)"
  #     - "traefik.http.routers.HSL-HEX.middlewares=HSL-HEX-stripprefix"
  #     - "traefik.http.middlewares.HSL-HEX-stripprefix.stripprefix.prefixes=/HSL-HEX"
  #     - "traefik.http.services.HSL-HEX.loadbalancer.server.port=3000"

  # RGB-CMYK:
  #   build: rgb-cmyk
  #   restart: "no"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.RGB-CMYK.rule=PathPrefix(`/RGB-CMYK`)"
  #     - "traefik.http.routers.RGB-CMYK.middlewares=RGB-CMYK-stripprefix"
  #     - "traefik.http.middlewares.RGB-CMYK-stripprefix.stripprefix.prefixes=/RGB-CMYK"
  #     - "traefik.http.services.RGB-CMYK.loadbalancer.server.port=3000"

  # CMYK-HSL:
  #   build: cmyk-hsl
  #   restart: "no"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.CMYK-HSL.rule=PathPrefix(`/CMYK-HSL`)"
  #     - "traefik.http.routers.CMYK-HSL.middlewares=CMYK-HSL-stripprefix"
  #     - "traefik.http.middlewares.CMYK-HSL-stripprefix.stripprefix.prefixes=/CMYK-HSL"
  #     - "traefik.http.services.CMYK-HSL.loadbalancer.server.port=3000"

#  <microservice-example-name>:
#    build: <microservice-example-name>
#    restart: "no"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.<microservice-example-name>.rule=PathPrefix(`/<microservice-example-name>`)"
#      - "traefik.http.routers.<microservice-example-name>.middlewares=<microservice-example-name>-stripprefix"
#      - "traefik.http.services.<microservice-example-name>.loadbalancer.server.port=3000"
#      - "traefik.http.middlewares.<microservice-example-name>-stripprefix.stripprefix.prefixes=/<microservice-example-name>"